var daniellebrown_pop = '<div class="poppy"><img src="images/sports_c.jpg" ><div class="poppy2"><h3>Danielle Brown Sports Centre</h3><ul><li><a target="_blank" href="http://www2.le.ac.uk/offices/sports">Sports Centre</a></li></ul></div></div>';
var richardattenborough_pop = '<div class="poppy"><img src="images/rac.jpg"/><div class="poppy2"><h3>Attenborough Arts Centre, Lancaster Road, LE1 7HA</h3><ul><li><a target="_blank" href="http://www.le.ac.uk/catering">Cafe/Restaurant (The Arts Bar)</a></li><li><a target="_blank" href="http://www2.le.ac.uk/hosted/attenborougharts">Attenborough Arts Centre</a></li><li><a target="_blank" href="http://www2.le.ac.uk/institution/music">Music</a></li></ul></div></div>';
var rattray_pop = '<div class="poppy"><img src="images/rattray.jpg"><div class="poppy2"><h3>Rattray Lecture Theatre</h3><ul><li><a target="_blank" href="http://www.le.ac.uk/catering">Cafe/Restaurant (Planets)</a></li><li>Lecture Theatre</li></ul></div></div>';
var percygee_pop = '<div class="poppy"><img src="images/percygee.jpg"><div class="poppy2"><h3>Percy Gee Students\' Union</h3><ul><li>Bank (Santander)</li><li><a target="_blank" href="http://www.leicesterunion.com">Cafe/Restaurant (1923)</a></li><li><a target="_blank" href="http://www.leicesterunion.com">Cafe/Restaurant (The Common Room)</a></li><li><a target="_blank" href="http://www.o2academyleicester.co.uk/">O2 Academy</a></li><li><a target="_blank" href="http://www.leicesterunion.com">Shop (Nourish)</a></li><li><a target="_blank" href="http://www.leicesterunion.com">Shop (Ryman)</a></li><li><a target="_blank" href="http://www.leicesterunion.com">Shop (Starbucks)</a></li><li><a target="_blank" href="http://www.leicesterunion.com">Students\' Union</a></li></ul></div></div>';
var michaelatiyah_pop = '<div class="poppy"><img src="images/atiyah.jpg"><div class="poppy2"><h3>Michael Atiyah Building</h3><ul><li><a target="_blank" href="http://www2.le.ac.uk/departments/mathematics">Mathematics</a> - Also within College House</li><li><a target="_blank" href="http://www2.le.ac.uk/departments/physics/research/src/welcome-to-the-space-research-centre">Space Research Centre</a></li></ul></div></div>';
var hodgkin_pop = '<div class="poppy"><img src="images/hodgkin.jpg"><div class="poppy2"><h3>Hodgkin Building</h3><ul><li>Mechanisms of Human Toxicity, Centre for</li><li>Toxicology Unit</li></ul></div></div>';
var gatehouse_pop = '<div class="poppy"><img src="images/chaplaincy.jpg"><div class="poppy2"><h3>Gatehouse Chaplaincy Centre</h3><ul><li><a target="_blank" href="http://www2.le.ac.uk/institution/chaplaincy/">Chaplaincy</a></li></ul></div></div>';
var library_pop = '<div class="poppy"><img src="images/library.jpg"><div class="poppy2"><h3>David Wilson Library</h3><ul><li><a target="_blank" href="http://www.le.ac.uk/accessability">AccessAbility Centre</a></li><li><a target="_blank" href="http://www.le.ac.uk/bookshop">Bookshop</a></li><li><a target="_blank" href="http://www2.le.ac.uk/offices/ithelp">IT Help Zone</a></li><li><a target="_blank" href="http://www2.le.ac.uk/library">Library</a></li><li><a target="_blank" href="http://www.le.ac.uk/catering">Library Cafe</a></li><li>Student Learning Centre</li></ul></div></div>';
var charleswilson_pop = '<div class="poppy"><img src="images/charleswilson.jpg"><div class="poppy2"><h3>Charles Wilson Building</h3><ul><li><a  href="http://www.le.ac.uk/catering">Cafe/Restaurant (chi)</a></li><li><a target="_blank" href="http://www.le.ac.uk/catering">Cafe/Restaurant (City Side)</a></li><li><a target="_blank" href="http://www.le.ac.uk/catering">Cafe/Restaurant (delic!ous)</a></li><li><a target="_blank" href="http://www.le.ac.uk/catering">Cafe/Restaurant (Park Side)</a></li><li><a target="_blank" href="http://www.le.ac.uk/careers">Career Development Service</a></li><li>Counselling</li><li>Student and Financial Administration</li><li>Student Welfare</li><li>Visa and Immigration Advice</li></ul></div></div>';
var biocomputer_pop = '<div class="poppy"><img src="images/computercentre.jpg"><div class="poppy2"><h3>Computer Centre</h3><ul><li><a target="_blank" href="http://www2.le.ac.uk/offices/itservices">IT Services</a> - Also within Prospect House</li></ul></div></div>';
var attenboroughseminar_pop = '<div class="poppy"><img src="images/attenborough_s.jpg"><div class="poppy2"><h3>Attenborough Seminar Block</h3><ul><li>Film theatre</li></ul></div></div>';
var museumstudies_pop = '<div class="poppy"><img src="images/museumstudies.jpg"><div class="poppy2"><h3>Museum Studies Building, 19 University Road, LE1 7RF</h3><ul><li><a target="_blank" href="http://www2.le.ac.uk/departments/museumstudies">Museum Studies</a></li></ul></div></div>';
var education_pop = '<div class="poppy"><img src="images/nophoto.png"><div class="poppy2"><h3>School of Education Building, 21 University Road, LE1 7RF</h3><ul><li><a target="_blank" href="http://www2.le.ac.uk/departments/education">School of Education</a></li></ul></div></div>';
var thefriars_pop = '<div class="poppy"><img src="images/nophoto.png"><div class="poppy2"><h3>The Friars, 154 Upper New Walk, LE1 7QA</h3><ul><li><a target="_blank" href="http://www2.le.ac.uk/departments/criminology">Criminology</a></li></ul></div></div>';
var learninginnovation_pop = '<div class="poppy"><img src="images/nophoto.png"><div class="poppy2"><h3>103-105 Princess Road East, LE1 7LG</h3><ul><li><a target="_blank" href="http://www.le.ac.uk/ili">Leicester Learning Institute</a></li></ul></div></div>';
var lifelonglearning_pop = '<div class="poppy"><img src="images/nophoto.png"><div class="poppy2"><h3>128 Regent Road, LE1 7PA</h3><ul><li><a target="_blank" href="http://www2.le.ac.uk/departments/lifelong-learning">Vaughan Centre for Lifelong Learning</a> - Also within 14 Salisbury Road, LE1 7QR</li></ul></div></div>';
var collegehouse_pop = '<div class="poppy"><img src="images/collegehouse.jpg"><div class="poppy2"><h3>College House</h3><ul><li><a target="_blank" href="http://www2.le.ac.uk/departments/mathematics">Mathematics</a> - Also within the Michael Atiyah Building</li></ul></div></div>';
var kenedwards_pop = '<div class="poppy"><img src="images/kenedwards.jpg"><div class="poppy2"><h3>Ken Edwards Building</h3><ul><li><a target="_blank" href="http://www2.le.ac.uk/departments/management/research/units/clms/">Centre for Labour Market Studies (CLMS)</a></li><li><a target="_blank" href="http://www2.le.ac.uk/departments/management">Management</a></li></ul><h4>Rooms</h4><p>Find the Ken Edwards Building in the <a target="_blank" href="http://www2.le.ac.uk/services/rooms/ken-edwards">rooms directory</a></p></div></div>';

var fieldingjohnson_pop = '<div class="poppy"><img src="images/fieldingjohnson.jpg"><div class="poppy2"><h3>Fielding Johnson Building</h3><ul><li>Administration and Reception</li><li><a target="_blank" href="http://www2.le.ac.uk/offices/cap/">External Relations</a> - Also within Freemen\'s Cottages</li><li><a target="_blank" href="http://www2.le.ac.uk/offices/international">International Office</a></li><li><a target="_blank" href="http://www2.le.ac.uk/departments/law">Law</a></li><li>Management Law and Industrial Relations Centre</li><li>Peter Williams Lecture Theatre - Entrance via South Wing</li><li><a target="_blank" href="http://www2.le.ac.uk/offices/estates/services/day-to-day-services/Security">Security Lodge</a></li><li><a target="_blank" href="http://www2.le.ac.uk/offices/sas2">Student and Academic Services</a> - Also within the David Wilson Library and Charles Wilson Building</li></ul><h4>Rooms</h4><p>Find the Fielding Johnson Building in the <a target="_blank" href="http://www2.le.ac.uk/services/rooms/fielding-johnson">rooms directory</a></p></div></div>';

var msb_pop = '<div class="poppy"><img src="images/msb.jpg"><div class="poppy2"><h3>Maurice Shock Medical Sciences Building</h3><ul><li><a target="_blank" href="http://www2.le.ac.uk/offices/itservices">Audio Visual Services</a></li><li><a target="_blank" href="http://www.le.ac.uk/catering">Cafe/Restaurant (The IV)</a></li><li><a target="_blank" href="http://www2.le.ac.uk/departments/cpp">Cell Physiology and Pharmacology</a> - Also within the Henry Wellcome Building</li><li><a target="_blank" href="http://www2.le.ac.uk/departments/iii">Infection, Immunity and Inflammation</a></li><li><a target="_blank" href="http://www2.le.ac.uk/departments/msce">Medical and Social Care Education</a></li><li><a target="_blank" href="http://www2.le.ac.uk/colleges/medbiopsych">Medicine, Biological Sciences and Psychology College Office</a></li><li><a target="_blank" href="http://www2.le.ac.uk/departments/msce">Leicester Medical School</a></li></ul><h4>Rooms</h4><p>Find the Maurice Shock Medical Sciences Building in the <a target="_blank" href="http://www2.le.ac.uk/services/rooms/maurice-shock">rooms directory</a></p></div></div>';
var astleyclarke_pop = '<div class="poppy"><img src="images/astleyclarke.jpg"><div class="poppy2"><h3>Astley Clarke Building</h3><ul><li><a target="_blank" href="http://www2.le.ac.uk/departments/economics">Economics</a></li></ul><h4>Rooms</h4><p>Find the Astley Clarke Building in the <a target="_blank" href="http://www2.le.ac.uk/services/rooms/astley-clarke">rooms directory</a></p></div></div>';
var computerscience_pop = '<div class="poppy"><img src="images/computerscience.jpg"><div class="poppy2"><h3>Computer Science Building</h3><ul><li><a target="_blank" href="http://www2.le.ac.uk/departments/computer-science">Computer Science</a></li></ul></div></div>';
var archaeology_pop = '<div class="poppy"><img src="images/archaeology.jpg"><div class="poppy2"><h3>Archaeology and Ancient History Building</h3><ul><li><a target="_blank" href="http://www2.le.ac.uk/departments/archaeology">Archaeology and Ancient History</a></li></ul><h4>Rooms</h4><p>Find the Archaeology and Ancient History Building in the <a target="_blank" href="http://www2.le.ac.uk/services/rooms/archaeology">rooms directory</a></p></div></div>';
var physics_pop = '<div class="poppy"><img src="images/physics.jpg"><div class="poppy2"><h3>Physics and Astronomy Building</h3><ul><li><a target="_blank" href="http://www2.le.ac.uk/departments/physics">Physics and Astronomy</a></li></ul><h4>Rooms</h4><p>Find the Physics and Astronomy Building in the <a target="_blank" href="http://www2.le.ac.uk/services/rooms/physics">rooms directory</a></p></div></div>';
var henrywellcome_pop = '<div class="poppy"><img src="images/henrywellcome.jpg"><div class="poppy2"><h3>Henry Wellcome Building</h3><ul><li><a target="_blank" href="http://www2.le.ac.uk/departments/biochemistry">Biochemistry</a> - Also within the Adrian Building</li><li><a target="_blank" href="http://www2.le.ac.uk/departments/biologicalsciences">Biological Sciences</a> - Also within the Adrian Building</li><li><a target="_blank" href="http://www2.le.ac.uk/partnership/lcrc">Cancer Research Centre (CRUK Leicester Centre)</a></li><li><a target="_blank" href="http://www2.le.ac.uk/departments/cpp">Cell Physiology and Pharmacology</a> - Also within the Maurice Shock Medical Sciences Building</li><li><a target="_blank" href="http://www2.le.ac.uk/departments/psychology">Clinical Psychology</a></li><li><a target="_blank" href="http://www2.le.ac.uk/departments/psychology">Psychology</a></li></ul><h4>Rooms</h4><p>Find the Henry Wellcome Building in the <a target="_blank" href="http://www2.le.ac.uk/services/rooms/henry-wellcome">rooms directory</a></p></div></div>';
var adrian_pop = '<div class="poppy"><img src="images/adrian.jpg"><div class="poppy2"><h3>Adrian Building</h3><ul><li><a target="_blank" href="http://www2.le.ac.uk/departments/biochemistry">Biochemistry</a> - Also within the Henry Wellcome Building</li><li><a target="_blank" href="http://www2.le.ac.uk/departments/biology">Biology</a></li><li><a target="_blank" href="http://www2.le.ac.uk/departments/biologicalsciences">Biological Sciences</a> - Also within the Henry Wellcome Building</li><li><a target="_blank" href="http://www2.le.ac.uk/departments/genetics">Genetics</a></ul><h4>Rooms</h4><p>Find the Adrian Building in the <a target="_blank" href="http://www2.le.ac.uk/services/rooms/adrian">rooms directory</a></p></div></div>';
var bennett_pop = '<div class="poppy"><img src="images/bennett.jpg"><div class="poppy2"><h3>Bennett Building</h3><ul><li><a target="_blank" href="http://www2.le.ac.uk/departments/geography">Geography</a></li><li><a target="_blank" href="http://www2.le.ac.uk/departments/geology">Geology</a></li></ul><h4>Rooms</h4><p>Find the Bennett Building and Bennett Link in the <a target="_blank" href="http://www2.le.ac.uk/services/rooms/bennett">rooms directory</a></p></div></div>';
var engineering_pop = '<div class="poppy"><img src="images/engineering.jpg"><div class="poppy2"><h3>Engineering Building</h3><ul><li><a target="_blank" href="http://www2.le.ac.uk/departments/engineering">Engineering</a></li></ul><h4>Rooms</h4><p>Find the Engineering Building in the <a target="_blank" href="http://www2.le.ac.uk/services/rooms/engineering">rooms directory</a></p></div></div>';
var attenboroughtower_pop = '<div class="poppy"><img src="images/attenborough_t.jpg"><div class="poppy2"><h3>Attenborough Tower</h3><ul><li><a target="_blank" href="http://www2.le.ac.uk/departments/americanstudies">American Studies</a></li><li><a target="_blank" href="http://www2.le.ac.uk/colleges/ssah">College of Social Sciences Arts and Humanities College Offices</a></li><li><a target="_blank" href="http://www2.le.ac.uk/departments/english">English</a></li><li>Film Theatre</li><li><a target="_blank" href="http://www2.le.ac.uk/departments/history">History</a></li><li><a target="_blank" href="http://www2.le.ac.uk/departments/arthistory">History of Art and Film</a></li><li><a target="_blank" href="http://www2.le.ac.uk/departments/modern-languages">Modern Languages</a></li><li><a target="_blank" href="http://www2.le.ac.uk/departments/politics">Politics and International Relations</a></li><li><a target="_blank" href="http://www2.le.ac.uk/departments/victorian">Victorian Studies Centre</a></li></ul> <h4>Rooms</h4> <p>Find the Attenborough Tower and Attenborough Seminar Block in the <a target="_blank" href="http://www2.le.ac.uk/services/rooms/attenborough">rooms directory</a></p></div></div>';
var georgeporter_pop = '<div class="poppy"><img src="images/georgeporter.jpg"><div class="poppy2"><h3>George Porter Building</h3><ul><li><a target="_blank" href="http://www2.le.ac.uk/departments/chemistry">Chemistry</a></li></ul><h4>Rooms</h4><p>Find the George Porter Building in the <a target="_blank" href="http://www2.le.ac.uk/services/rooms/george-porter">rooms directory</a></p></div></div>';
var studentcounselling_pop = '<div class="poppy"><img src="images/studentcounselling.jpg"><div class="poppy2"><h3>Freemen\'s Cottages</h3><ul><li><a target="_blank" href="http://www2.le.ac.uk/offices/cap/marcomms/creative/">External Relations - Creative Services</a></li><li><a target="_blank" href="http://www2.le.ac.uk/offices/ssds/counselling/">Student Counselling and Wellbeing Service</a></li></ul></div></div>';
var freemanscommon_pop = '<div class="poppy"><img src="images/nophoto.png"><div class="poppy2"><h3>Freemen\'s Common 153/167 Welford Road, Leicester, LE2 6BF</h3><ul><li><a target="_blank" href="http://www2.le.ac.uk/offices/accommodation/student-accommodation/self-catered-city-living/freemens-common/freemens-common-houses">Freemen\'s Common</a></div></div>';

var centreformedicine_pop = '<div class="poppy"><img src="images/medicine.jpg"><div class="poppy2"><h3>Leicester Medical School, Centre for Medicine, Leicester, LE1 7HA</h3><ul><li><a target="_blank" href="http://www2.le.ac.uk/departments/health-sciences">Health Sciences</a></li><li><a target="_blank" href="http://www2.le.ac.uk/departments/medicine">Leicester Medical School</a></li><li><a target="_blank" href="http://www2.le.ac.uk/departments/npb">NPB (Neuroscience, Psychology and Behaviour)</a></li></div></div>';





var opal_pop = '<div class="poppy"><img src="images/opal.jpg"><div class="poppy2"><h3>Opal Court - 60 Lancaster Road, Leicester, LE1 7HA</h3><ul><li><a target="_blank" href="http://www2.le.ac.uk/offices/accommodation/student-accommodation/self-catered-city-living/opal-court-1/opal-court">Opal Court</a></li></ul></div></div>';
var salisbury_pop = '<div class="poppy"><img src="images/nophoto.png"><div class="poppy2"><h3>Salisbury Road Houses, Leicester, LE2 7EG</h3><ul><li>Various properties in and around the <a target="_blank" href="http://www2.le.ac.uk/offices/accommodation/student-accommodation/self-catered-city-living/salisbury-houses-1/salisbury-houses">Salisbury Road</a> and Regent Road area of Leicester.</li></ul></div></div>';
var nixon_pop = '<div class="poppy"><img src="images/nixon.jpg"><div class="poppy2"><h3>Nixon Court - 33 Putney Road, Leicester, LE2 7TG</h3><ul><li><a target="_blank" href="http://www2.le.ac.uk/offices/accommodation/student-accommodation/self-catered-city-living/nixon-court-1/nixon-court">Nixon Court</a></li></ul></div></div>';
var marygee_pop = '<div class="poppy"><img src="images/nophoto.png"><div class="poppy2"><h3>Mary Gee Student Houses - 101/107 Ratcliffe Road, Leicester, LE2 3TE</h3><ul><li><a target="_blank" href="http://www2.le.ac.uk/offices/accommodation/student-accommodation/self-catered-city-living/mary-gee/mary-gee-houses">Mary Gee Student Houses</a></li></ul></div></div>';
var johnfoster_pop = '<div class="poppy"><img src="images/johnfoster.jpg"><div class="poppy2"><h3>John Foster Hall - Manor Road, Oadby, Leicester, LE2 2LG</h3><ul><li><a target="_blank" href="http://www2.le.ac.uk/offices/accommodation/student-accommodation/oadby-student-village/john-foster-hall-1/john-foster-hall">John Foster Hall</a></li></ul></div></div>';
var digby_pop = '<div class="poppy"><img src="images/digby.jpg"><div class="poppy2"><h3>Digby Hall - Stoughton Drive South, Leicester, LE2 2NB</h3><ul><li><a target="_blank" href="http://www2.le.ac.uk/offices/accommodation/student-accommodation/oadby-student-village/beaumont-and-digby-hall-1/beaumont-and-digby-hall">Digby Hall</a></li></ul></div></div>';
var beaumont_pop = '<div class="poppy"><img src="images/beaumont.jpg"><div class="poppy2"><h3>Beaumont Hall - Stoughton Drive South, Leicester, LE2 2NA</h3><ul><li><a target="_blank" href="http://www2.le.ac.uk/offices/accommodation/student-accommodation/oadby-student-village/beaumont-and-digby-hall-1/beaumont-and-digby-hall">Beumont Hall</a></li></ul></div></div>';
var gilbert_pop = '<div class="poppy"><img src="images/gilbert.jpg"><div class="poppy2"><h3>Gilbert Murray/Stamford Hall - Manor Road, Oadby, Leicester, LE2 2LH</h3><ul><li><a target="_blank" href="http://www2.le.ac.uk/offices/accommodation/student-accommodation/oadby-student-village/gilbert-murray-and-stamford-1/gilbert-murray-and-stamford">Gilbert Murray/Stamford Hall</a></li></ul></div></div>';
var healthsciences_pop = '<div class="poppy"><img src="images/nophoto.png"><div class="poppy2"><h3>Health Sciences, 22-28 Princess Road West, LE1 6TP</h3><ul><li><a target="_blank" href="http://www2.le.ac.uk/departments/health-sciences">Health Sciences</a></li></ul></div></div>';
var bankfield_pop = '<div class="poppy"><img src="images/nophoto.png"><div class="poppy2"><h3>Bankfield House, 132 New Walk, LE1 7JA</h3><ul><li><a target="_blank" href="http://www2.le.ac.uk/departments/media">Media and Communication</a></li></ul></div></div>';
var brookfield_pop = '<div class="poppy"><img src="images/nophoto.png"><div class="poppy2"><h3>Brookfield - LE2 1RQ</h3><ul><li>Brookfield Postgraduate Teaching Centre</li><li><a href="http://www2.le.ac.uk/offices/estates" target="_blank">Estates</a></li><li><a href="http://www2.le.ac.uk/offices/finance" target="_blank">Finance</a> - Also within the Fielding Johnson Building</li><li><a target="_blank" href="http://www2.le.ac.uk/offices/hr/">Human Resources</a></li></ul></div></div>';
var collegecourt_pop = '<div class="poppy"><img src="images/nophoto.png"><div class="poppy2"><h3>College Court, Knighton Road, LE2 3T</h3><ul><li><a target="_blank" href="http://www.collegecourt.co.uk">College Court Conference Centre</a></li></ul></div></div>';
var glenfield_pop = '<div class="poppy"><img src="images/nophoto.png"><div class="poppy2"><h3>Glenfield Hospital, Groby Rd, LE3 9QP</h3><ul><li><a target="_blank" href="http://www.leicestershospitals.nhs.uk/">University of Leicester Hospitals website</a></li></ul></div></div>';
var royal_pop = '<div class="poppy"><img src="images/nophoto.png"><div class="poppy2"><h3>Leicester Royal Infirmary, Infirmary Square, LE1 5WW</h3><ul><li><a target="_blank" href="http://www.leicestershospitals.nhs.uk/">University of Leicester Hospitals website</a></li></ul></div></div>';
var general_pop = '<div class="poppy"><img src="images/nophoto.png"><div class="poppy2"><h3>Leicester General Hospital, Gwendolen Rd, LE5 4PW</h3><ul><li><a target="_blank" href="http://www.leicestershospitals.nhs.uk/">University of Leicester Hospitals website</a></li></ul></div></div>';
var kilpatrick_pop = '<div class="poppy"><img src="images/nophoto.png"><div class="poppy2"><h3>Robert Kilpatrick Clinical Sciences Building, LE1 5WW</h3></div></div>';
var prospecthouse_pop = '<div class="poppy"><img src="images/nophoto.png"><div class="poppy2"><h3>Prospect House, 94 Regent Road, LE1 7DA</h3><ul><li><a target="_blank" href="http://www2.le.ac.uk/offices/itservices">IT Services</a> - Also within Computer Centre</li><li>International Study Centre</li></ul></div></div>';

var readsonhouse_pop = '<div class="poppy"><img src="images/nophoto.png"><div class="poppy2"><h3>Readson House, 96-98 Regent Road, LE1 7DF</h3><ul><li><a target="_blank" href="http://www2.le.ac.uk/offices/eltu/">English Language Teaching Unit</a></li><li><a target="_blank" href="http://www2.le.ac.uk/projects/g-step">G-STEP</a></li></ul></div></div>';
var road_pop = '<div class="poppylarge"><h3>Leicester by road</h3><p>The University\'s postcode is <strong>LE1 7RH</strong>. All campus access is via University Road. For Leicester Medical School departments based in local hospitals, please visit the <a target="_blank" href="http://www.leicestershospitals.nhs.uk" target="_blank">University Hospitals of Leicester NHS Trust website</a>.</p><form action="http://maps.google.co.uk/maps" enctype="application/x-www-form-urlencoded" method="get" target="_blank"><label for="saddr"><h4>Directions</h4></label><p>Enter your postcode and select a destination to get driving directions.</p><div class="postcode"><label>Postcode:</label><input id="saddr" name="saddr" type="text"></div><div class="destination"><label>Destination:</label><select name="daddr"><option name="daddr" value="LE17RH">University main campus</option><option name="daddr" value="LE22NA">Beaumont Hall</option><option name="daddr" value="LE21RQ">Brookfield</option><option name="daddr" value="LE23TQ">College Court</option><option name="daddr" value="LE22NF">Digby Hall</option><option name="daddr" value="LE26BF">Freemen\'s Common</option><option name="daddr" value="LE22LG">Gilbert Murray/Stamford Hall</option><option name="daddr" value="LE39QP">Glenfield Hospital</option><option name="daddr" value="LE22LG">John Foster Hall</option><option name="daddr" value="LE22LH">Leicester Conferences</option><option name="daddr" value="LE21RQ">Leicester General</option><option name="daddr" value="LE15WW">Leicester Royal Infirmary</option><option name="daddr" value="LE23TE">Mary Gee Student Houses</option><option name="daddr" value="LE27TG">Nixon Court</option><option name="daddr" value="LE17HA">Opal Court</option><option name="daddr" value="LE17QR">Salisbury Road Houses</option><option name="daddr" value="LE17PA">Vaughan Centre</option></select></div><div class="directions"><input type="submit" value="Get Directions"><input name="hl" type="hidden" value="en"></div></form><h4>One-Way System</h4><p>Please note that there is a one-way system around campus with all vehicles entering at Entrance 1 (Wyggeston Drive, next to Danielle Brown Sports Centre). There is no vehicular access at Entrance 2 (Mayor\'s Walk).</p><h4>Useful links</h4><ul><li><a target="_blank" href="http://www.leicester.gov.uk/your-council-services/transport-traffic/traffic-travel/bycar/">Leicester City Council Traffic and Travel site</a> including up-to-date information on incidents and roadworks</li><li><a target="_blank" href="http://www.theaa.com/traffic-news/index.jsp">AA Roadwatch</a></li></ul></div>';

var onesalisbury_pop = '<div class="poppy"><img src="images/nophoto.png"><div class="poppy2"><h3>1 Salisbury Road, LE1 7QR</h3><ul><li><a target="_blank" href="http://www2.le.ac.uk/departments/history">School of History </a> - Also within 6 Salisbury Road</li><li><a target="_blank" href="http://www.le.ac.uk/emoha/">East Midlands Oral History Archive</a></li></ul></div></div>';

var threefivesalisbury_pop = '<div class="poppy"><img src="images/nophoto.png"><div class="poppy2"><h3>3/5 Salisbury Road, LE1 7QR</h3><ul><li><a target="_blank" href="http://www2.le.ac.uk/departments/urbanhistory">Centre for Urban History</a></li><li><a target="_blank" href="http://www2.le.ac.uk/centres/elh">Centre for English Local History</a></li></ul></div></div>';

var sevenninesalisbury_pop = '<div class="poppy"><img src="images/nophoto.png"><div class="poppy2"><h3>7/9 Salisbury Road, LE1 7QR</h3><ul><li><a target="_blank" href="http://www2.le.ac.uk/centres/cmh/">Centre for Medical Humanities</a></li><li><a target="_blank" href="http://www2.le.ac.uk/centres/csn">Centre for Systems Neuroscience</a></li></ul></div></div>';

var fourteensalisbury_pop = '<div class="poppy"><img src="images/nophoto.png"><div class="poppy2"><h3>14 Salisbury Road, LE1 7QR</h3><ul><li><a target="_blank" href="http://www2.le.ac.uk/departments/lifelong-learning">Vaughan Centre for Lifelong Learning</a> - Also within 128 Regent Road, LE1 7PA</li></ul></div></div>';

var sixsalisbury_pop = '<div class="poppy"><img src="images/nophoto.png"><div class="poppy2"><h3>6 Salisbury Road, LE1 7QR</h3><ul><li><a target="_blank" href="http://www2.le.ac.uk/departments/history">School of History </a> - Also within 1 Salisbury Road</li></ul></div></div>';

var onehundredfourregentroad_pop = '<div class="poppy"><img src="images/nophoto.png"><div class="poppy2"><h3>104 Regent Road, LE1 7LT</h3><ul><li><a href="http://www2.le.ac.uk/departments/psychology/postgraduate/clinical-psychology">Doctorate in Clinical Psychology</a></li></ul></div></div>';

var air_pop = '<div class="poppylarge"><h3>Leicester by air</h3><h4>East Midlands Airport</h4><p>The nearest airport to Leicester is East Midlands Airport, which serves Leicester, Derby and Nottingham. The airport has direct flights to more than 90 destinations in 28 countries as well as many internal flights within the UK. The Leicester Skylink bus service connects East Midlands Airport with St Margaret\'s Bus Station, 24 hours a day, seven days a week. Skylink buses run every 30 minutes during the day and hourly at night. See the coach page for details of how to get from St Margaret\'s to the  University.</p><h4>Other Airports</h4><p>There are rail services from Leicester to Birmingham Airport (via Coleshill Parkway), Luton Airport (via Luton Aiport Parkway) and Stansted Airport. There is a direct coach service from Leicester to Heathrow Airport and Gatwick Airport. NB. There is an airport just outside the city called Leicester Airport but this is a small airfield only suitable for light aircraft and should only be considered if you are flying your own plane!</p><h4>Useful links</h4><ul><li><a target="_blank" href="http://www.eastmidlandsairport.com/" target="_blank">East Midlands Airport</a></li><li><a target="_blank" href="http://www.eastmidlandsairport.com/emaweb.nsf/Content/SkyLinkLeicester" target="_blank">Leicester Skylink</a></li></ul><h4>Useful contacts</h4><ul><li>East Midlands Airport (from within UK): 0871 919 9000</li><li>East Midlands Airport (from outside UK): +44 1332 852 852</li><li>East Midlands Airport disability service (OCS): 01332 818426</li></ul></div>';
var bus_pop = '<div class="poppylarge"><h3>Leicester by bus/coach</h3><p>Leicester is served by a wide range of coach services, mostly operated by National Express. Although slower than rail travel, journeys by coach are usually considerably cheaper and often have a smaller carbon footprint. In addition, there are direct coach links to Leicester from cities which do not have direct rail links, such as Manchester and Coventry. A coach from Leicester to London takes about three hours.</p><p>There are regular direct buses between Leicester and Loughborough (Arriva no.126/127) and between Leicester and Northampton (Stagecoach no.X7).</p><h3>Getting from the coach station to the campus</h3><h4>Bus or Taxi</h4><ul><li>National Express coaches (and the X7 bus) stop at St Margaret\'s Bus Station, which is on the other side of the city from the University.</li><li>The no.48 bus, operated by Arriva, leaves St Margaret\'s every 15 minutes and takes about ten minutes to reach the University. (NB. The return journey is the no.47.)</li><li>The no.80 bus, also Arriva, leaves St Margaret\'s every 30 minutes and continues past the University to the Halls of Residence in Oadby. When returning, be aware that the 80A operates largely the same route but does not go to the railway station or city centre.</li><li>Alternatively there is a taxi rank outside St Margaret\'s.</li></ul><h4>On Foot</h4><p>If you\'re feeling fit and know your way through the city centre, the walk will take about 35-40 minutes.</p><p><a target="_blank" href="http://goo.gl/maps/eTjv7">View the walking route on a map with directions</a></p><h4>Useful links</h4><ul><li><a target="_blank" href="http://www.nationalexpress.com/" target="_blank">National Express </a>- for timetables, routes and tickets</li><li><a target="_blank" href="http://www.arrivabus.co.uk/serviceInformation.aspx?id=2758">Arriva no.47/48 bus</a> - route and timetable</li><li><a target="_blank" href="http://www.arrivabus.co.uk/serviceInformation.aspx?id=2763">Arriva no.80/80A bus</a> - route and timetable</li><li><a target="_blank" href="http://www.arrivabus.co.uk/serviceInformation.aspx?id=6121&r=UK">Arriva no.126/127 bus</a> - route and timetable</li><li><a target="_blank" href="http://www.stagecoachbus.com/timetables/NNX7July2008PP[1].pdf">Stagecoach no.X7 bus </a>- route and timetable</li></ul><h4>Useful contacts</h4><ul><li>National Express booking line: +44 (0) 8717 818181</li><li>(8am-8pm Monday to Saturday; 10am-8pm Sunday. Calls cost a maximum of 10 pence a minute for BT customers. Mobile and other networks may vary.)</li><li>National Express disabled persons travel helpline:  +44 (0) 8717 818179</li><li>National Express textphone: +44 (0) 121 455 0086</li><li>(for customers who are deaf or hard of hearing)</li><li><a target="_blank" href="http://www.travelineeastmidlands.co.uk">Traveline East Midlands</a> (public transport journey planner)</li></ul></div>';
var rail_pop = '<div class="poppylarge"><h3>Leicester by rail</h3><p>Leicester is just 69 minutes direct from London by train. There are also direct rail links to Birmingham, Sheffield, Nottingham, Derby, East Midlands Parkway (for <a class="internal-link" href="http://www2.le.ac.uk/maps/air" title="Air">East Midlands Airport</a>), Peterborough, Luton and Stansted Airport.</p><p>Leicester is on a direct line into St Pancras International, the home of Eurostar, and with just one change of train, you could be in Paris or Brussels by lunchtime. North-South train services through Leicester are run by East Midlands Trains, who also manage Leicester Station; East-West services are run by Cross-Country Trains.</p><h3>Getting to campus from the railway station</h3><h4>On Foot</h4><p>Leicester Railway Station is within walking distance of the University (15 minutes). From the station entrance,  turn left onto London Road, walk up the hill for about 400m, then turn right onto University Road and walk another 700m. The principal entrance to the Campus is Entrance 2, Mayor\'s Walk, on your left just before the Students’ Union.</p><p><a target="_blank" href="http://goo.gl/maps/Igvns" target="_blank">View this route on a map with directions</a></p><h4>By Bus</h4><ul><li>During <a target="_blank" href="http://www2.le.ac.uk/offices/governance/calendar/terms-and-semesters" title="Terms and Semesters">term-time</a>, you can catch a No. 80 bus, which is operated by Arriva and runs every 20 minutes. This takes less than five minutes to reach Mayor\'s Walk. The bus stop is located directly outside the station.</li></ul><ul><li>If you want to travel to the student accommodation (Oadby Student Village) from the train station you should again catch the No. 80 bus. This journey will take about 25 minutes.</li></ul><h4>Useful links</h4><ul><li><a target="_blank" href="http://www.eastmidlandstrains.co.uk/">East Midlands Trains</a> </li><li><a target="_blank" href="http://www.eastmidlandstrains.co.uk/EMTrains/YourDestinations/TownsAndCities/Leicester.htm">East Midlands Trains. Offers to and from Leicester</a></li><li><a target="_blank" href="http://www.crosscountrytrains.co.uk/">Cross-Country Trains</a></li><li><a target="_blank" href="http://www.rail.co.uk/">UK Railways on the net</a> (rail.co.uk) – for timetables, travel information and tickets</li><li><a target="_blank" href="http://www.arrivabus.co.uk/serviceInformation.aspx?id=2763">Arriva Number 80 bus</a> - timetable and route map</li></ul><h4>Useful contacts</h4><ul><li>National Rail Enquiries: <b>08457 48 49 50</b> </li><li>National Rail Enquiries from overseas: +<strong>44 (0) 20 7278 5240</strong> </li><li>(Please note: International rates apply)</li><li>National Rail Enquiries Textphone: <strong>0845 60 50 600</li><li></strong>(for customers with hearing imparements)</li></ul></div>'